/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Cliente;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Programador
 */
public class frm_personas extends javax.swing.JFrame {
    Cliente cliente;
    DefaultTableModel tbl_modelo;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_personas.class.getName());

    /**
     * Creates new form frm_personas
     */
    public frm_personas() {
        initComponents();
        cliente = new Cliente();
        tbl_modelo = new DefaultTableModel();
        String encabezado[]={"Nit","Nombres","Apellidos","Direccion","Telefono","Nacimiento"};
        tbl_modelo.setColumnIdentifiers(encabezado);
        tbl_clientes.setModel(tbl_modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtp_principal = new javax.swing.JTabbedPane();
        pa_clientes = new javax.swing.JPanel();
        lbl_tituloc = new javax.swing.JLabel();
        lbl_nitc = new javax.swing.JLabel();
        txt_nitc = new javax.swing.JTextField();
        lbl_nombresc = new javax.swing.JLabel();
        txt_nombresc = new javax.swing.JTextField();
        lbl_apellidosc = new javax.swing.JLabel();
        txt_apellidosc = new javax.swing.JTextField();
        lbl_direccionc = new javax.swing.JLabel();
        txt_direccionc = new javax.swing.JTextField();
        lbl_telefonoc = new javax.swing.JLabel();
        txt_telefonoc = new javax.swing.JTextField();
        lbl_fnc = new javax.swing.JLabel();
        txt_fnc = new javax.swing.JTextField();
        lbl_mensajec = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        jsp_clientes = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        pa_empleados = new javax.swing.JPanel();
        lbl_tituloe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tituloc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_tituloc.setText("Formulario Clientes");

        lbl_nitc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nitc.setText("Nit");

        lbl_nombresc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nombresc.setText("Nombres");

        lbl_apellidosc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_apellidosc.setText("Apellidos");

        lbl_direccionc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_direccionc.setText("Direccion");

        lbl_telefonoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_telefonoc.setText("Telefono");

        lbl_fnc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_fnc.setText("Nacimiento");

        lbl_mensajec.setText("0");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsp_clientes.setViewportView(tbl_clientes);

        javax.swing.GroupLayout pa_clientesLayout = new javax.swing.GroupLayout(pa_clientes);
        pa_clientes.setLayout(pa_clientesLayout);
        pa_clientesLayout.setHorizontalGroup(
            pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_clientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tituloc)
                .addGap(218, 218, 218))
            .addGroup(pa_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pa_clientesLayout.createSequentialGroup()
                        .addComponent(lbl_apellidosc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_apellidosc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_fnc)
                        .addGroup(pa_clientesLayout.createSequentialGroup()
                            .addComponent(lbl_telefonoc)
                            .addGap(26, 26, 26)
                            .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_guardar)
                                .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_telefonoc, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txt_fnc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_mensajec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pa_clientesLayout.createSequentialGroup()
                        .addComponent(lbl_direccionc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_direccionc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pa_clientesLayout.createSequentialGroup()
                        .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pa_clientesLayout.createSequentialGroup()
                                .addComponent(lbl_nombresc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_clientesLayout.createSequentialGroup()
                                .addComponent(lbl_nitc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nitc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombresc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jsp_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        pa_clientesLayout.setVerticalGroup(
            pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloc)
                .addGap(24, 24, 24)
                .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nitc)
                    .addComponent(txt_nitc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombresc)
                    .addComponent(txt_nombresc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellidosc)
                    .addComponent(txt_apellidosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccionc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_direccionc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefonoc)
                    .addComponent(txt_telefonoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fnc)
                    .addComponent(txt_fnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_mensajec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guardar)
                .addGap(26, 26, 26)
                .addComponent(jsp_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );

        jtp_principal.addTab("Clientes", pa_clientes);

        lbl_tituloe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_tituloe.setText("Formulario Empleados");

        javax.swing.GroupLayout pa_empleadosLayout = new javax.swing.GroupLayout(pa_empleados);
        pa_empleados.setLayout(pa_empleadosLayout);
        pa_empleadosLayout.setHorizontalGroup(
            pa_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_empleadosLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(lbl_tituloe)
                .addGap(219, 219, 219))
        );
        pa_empleadosLayout.setVerticalGroup(
            pa_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloe)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        jtp_principal.addTab("Empleados", pa_empleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try{
            //import javax.swing.JOptionPane;
            cliente.setNit(txt_nitc.getText());
            cliente.setNombres(txt_nombresc.getText());
            cliente.setApellidos(txt_apellidosc.getText());
            cliente.setDireccion(txt_direccionc.getText());
            cliente.setTelefono(txt_telefonoc.getText());
            cliente.setFecha_nacimiento(this.txt_fnc.getText());
            
            tbl_modelo.addRow(cliente.crear());
            this.tbl_clientes.setModel(tbl_modelo);
            JOptionPane.showMessageDialog(null, "Ingreso Exitoso","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            
            txt_nitc.setText(null);
            txt_nombresc.setText(null);
            txt_apellidosc.setText(null);
            txt_direccionc.setText(null);
            txt_telefonoc.setText(null);
            txt_fnc.setText(null);
            
        }catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage(),"Mensaje",JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_personas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JScrollPane jsp_clientes;
    private javax.swing.JTabbedPane jtp_principal;
    private javax.swing.JLabel lbl_apellidosc;
    private javax.swing.JLabel lbl_direccionc;
    private javax.swing.JLabel lbl_fnc;
    private javax.swing.JLabel lbl_mensajec;
    private javax.swing.JLabel lbl_nitc;
    private javax.swing.JLabel lbl_nombresc;
    private javax.swing.JLabel lbl_telefonoc;
    private javax.swing.JLabel lbl_tituloc;
    private javax.swing.JLabel lbl_tituloe;
    private javax.swing.JPanel pa_clientes;
    private javax.swing.JPanel pa_empleados;
    private javax.swing.JTable tbl_clientes;
    private javax.swing.JTextField txt_apellidosc;
    private javax.swing.JTextField txt_direccionc;
    private javax.swing.JTextField txt_fnc;
    private javax.swing.JTextField txt_nitc;
    private javax.swing.JTextField txt_nombresc;
    private javax.swing.JTextField txt_telefonoc;
    // End of variables declaration//GEN-END:variables
}
